FROM maven:3.9.3-sapmachine-17 AS build
COPY src /home/app/src
COPY pom.xml /home/app
RUN mvn -f /home/app/pom.xml clean package

FROM openjdk:17
COPY --from=build /home/app/target/todo-3.1.2.jar /usr/local/lib/todo.jar
EXPOSE 8080
EXPOSE 8443
ENTRYPOINT ["java","-jar","/usr/local/lib/todo.jar"]

