version: '3'
volumes:
  dbdata: {}
  ignore:
services:
  mysqldb:
    image: "mysql:latest"
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=todos
    volumes:
      - dbdata:/var/lib/mysql
  app:
    build: .
    depends_on:
      - mysqldb
    volumes:
      - ./:/todo-app/src
    ports:
      - "8080:8080"
    image: roasteg/todo-spring
